global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'trading_app'
    static_configs:
      - targets: ['trading_app:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

rule_files:
  - 'alerts.yml'
